contrib: copy new SPEC from plugsched-build
The new SPEC is more formal and sophisticated.

FIXME:
    This patch break rpmbuild, will fix it in later patch.

Signed-off-by: Yihao Wu <wuyihao@linux.alibaba.com>
Reviewed-by: Shanpei Chen <shanpeic@linux.alibaba.com>

diff --git a/module-contrib/plugsched-install b/module-contrib/plugsched-install
--- a/module-contrib/plugsched-install
+++ b/module-contrib/plugsched-install
@@ -1,22 +1,27 @@
 #!/bin/bash
 
 cursys=$(uname -r)
-mod=$(modinfo /usr/local/share/plugsched/plugsched.ko | grep vermagic | awk '{print $2}')
+modfile=/var/plugsched/$cursys/plugsched.ko
+mod=$(modinfo $modfile | grep vermagic | awk '{print $2}')
 
-not_install="/var/plugsched/plugsched-install-not"
-if [ -f "$not_install" ]; then
+skip="/var/plugsched/skip"
+if [ -f "$skip" ]; then
 	echo "Error: plugsched: cannot load plugsched, please update"
 	exit 1
 fi
 
+if ! /usr/local/bin/plugsched-verses-kpatch.py pre; then
+	echo "Error: there are hotfixes conflicting with plugsched. Exit."
+	exit 1
+fi
+
 if [ "$cursys" == "$mod" ]; then
-	/usr/bin/cp /usr/local/share/plugsched/plugsched.ko /tmp/plugsched_tmp.ko
-	/usr/local/bin/plugsched /tmp/plugsched_tmp.ko /proc/kallsyms
-	/usr/bin/touch $not_install
+	/usr/bin/cp $modfile /run/plugsched/plugsched.ko
+	/usr/local/bin/plugsched /run/plugsched/plugsched.ko /proc/kallsyms
+	/usr/bin/touch $skip
 	/usr/bin/sync
-	/usr/sbin/insmod /tmp/plugsched_tmp.ko
-	/usr/bin/rm -f $not_install
-	/usr/bin/rm -f /tmp/plugsched_tmp.ko
+	/usr/sbin/insmod /run/plugsched/plugsched.ko
+	/usr/bin/rm -f $skip
 else
 	echo "Error: kernel version is not same as plugsched version!"
 	exit 1
